version: '3.1'

services:

  mongo:
    image: mongo
    container_name: mongo-db
    ports:
      - 27017:27017
    volumes:
      - mongo-kotlin:/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

volumes:
  mongo-kotlin: